import requests
import urllib.parse

lst_categorias = [
    "Consultoria",
    "Pré-Dig.Energia",
    "Ges.Portifólio",
    "Ges.Energia",
    "AAi",
    "LEED.EB",
    "LEED.EB-Pesq.Auditorias",
    "LEED.NC",
    "LEED.CS",
    "LEED.CI",
    "LEED.DB+C",
    "EDGE-Expert",
    "BREEAM",
    "AQUA",
    "GBC.Casa",
    "PBE",
    "ISO.50001",
    "Rev.Energética",
    "NBR.15575",
    "Rev.Energética",
    "NBR.15575",
    "NBR.15200",
    "Proj.Sustentável",
    "Sim.Conf.Térmico",
    "Sim.Luminotécnica",
    "Sim.Energética",
    "Comission",
    "Recomission",
    "Retrocomission",
    "Cogeração",
    "Font.Renováveis",
    "Net-zero",
    "Impl-Elétrica",
    "Impl-LED",
    "Impl-FV",
    "Impl-Auto",
    "Impl-Hídrica",
    "Arq.Passiva",
    "Análise da Iluminação Natural",
    "Gestão da Implantação de Medida",
    "Consultoria de Projeto Eficiente",
    "Consultoria em Conclusão de Serviços",
    "Desempenho da Qualidade do Ar Interno",
    "Análise da Qualidade Ambiental Interna",
    "Análise do Sistema de Medição",
    "Qualidade da Iluminação Interior",
    "Pesquisa / Intelligence",
    "EDGE-Audit",
    "Gestão-Ambiental",
    "M&V",
    "PEE",
    "Intelligence",
    "Sol.Inovadoras-EE",
    "Prog.Nac.Inovadoras-EE",
    "Guia-B.Práticas",
    "Doc.Técnicos",
    "Pol.Públicas",
    "Benchmarking",
    "Comp.Sustentáveis",
    "Plan.EE",
    "Startup",
    "Estudos e pesquisas",
    "Plataforma",
    "Financiamento de EE",
    "Treinamentos",
    "Trein_NC-Proj.Ref.Retrofit",
    "Trein_EB-Dig.Gestão",
    "Trein_Tec.Sist-Monitoramento",
    "Trein_Aval.Gest.Proj.Energia",
    "Trein_Certificações (especificar",
    "Trein_Efic.Energética",
    "Trein_NBR-15575",
    "Derivados",
    "LEED.NC-Sim.Conf.Térmico",
    "GBC.Casa-NBR.15575",
    "LEED.NC-Sim.Energética",
    "LEED.EBv4-Dig.Energia",
    "LEED.EBv3-Dig.Energia",
    "LEED.EBv3-Comissionamento",
    "LEED.EBv4-Qual.Ar",
    "LEED.EBv4-Ilum.Int",
    "LEED.EBv4-Comissi",
]

for categoria in lst_categorias:
    url = f"http://127.0.0.1:5000/proposta/adicionar-produto-categoria?categoria={urllib.parse.quote(categoria)}"

    r = requests.get(url)

    print(r.content)